# Generated by Django 5.0.3 on 2024-03-20 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('other_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('passport_size', models.ImageField(blank=True, upload_to='pictures/')),
                ('nida_birth', models.ImageField(blank=True, upload_to='pictures/')),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widow', 'Widow'), ('Divorced', 'Divorced')], max_length=50)),
                ('nationality', models.ForeignKey(default='Tanzania', on_delete=django.db.models.deletion.CASCADE, to='mainapp.nationality')),
            ],
        ),
    ]
