# Generated by Django 4.1.7 on 2024-03-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='nida_birth',
            field=models.FileField(blank=True, upload_to='pictures/'),
        ),
    ]
