# Generated by Django 4.1.7 on 2024-03-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_applicant_nida_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('accepted', 'accepted'), ('pending', 'pending')], default='pending', max_length=50),
        ),
    ]
