# Generated by Django 4.1.7 on 2024-03-21 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.nationality'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
    ]
