# Generated by Django 4.1.7 on 2024-03-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_employment_alter_applicant_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employment',
            old_name='business',
            new_name='employer',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
    ]
