# Generated by Django 5.0.3 on 2024-03-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_business_employment_employer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_per_annum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spouse_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('any_other_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('have_any_loan', models.BooleanField(default=False)),
                ('amount_of_loan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=50),
        ),
    ]
