# Generated by Django 5.0.3 on 2024-03-24 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_financialinformation_alter_applicant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must start with '+255' followed by 9 digits.", regex='^\\+255\\d{9}$')])),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted')], default='pending', max_length=50),
        ),
    ]
