# Generated by Django 4.1.7 on 2024-03-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_project_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_location', models.CharField(max_length=200)),
                ('house_type', models.CharField(choices=[('apartment', 'apartment'), ('bungalow', 'bungalow'), ('ghorofa', 'ghorofa'), ('ya kawaida', 'ya kawaida')], max_length=200)),
                ('number_of_rooms', models.IntegerField()),
                ('house_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_of_payment', models.CharField(max_length=200)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.project')),
            ],
        ),
    ]
