# Generated by Django 5.0.3 on 2024-04-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_dependant_alter_applicant_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependant',
            old_name='date_ofbirth',
            new_name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('accepted', 'accepted'), ('pending', 'pending')], default='pending', max_length=50),
        ),
    ]
