# Generated by Django 4.1.7 on 2024-04-03 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0018_applicant_user_contact_user_dependant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('pending', 'pending'), ('accepted', 'accepted')], default='pending', max_length=50),
        ),
    ]
